version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./tools/Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    networks:
      - rust-net

  user:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - rust-net

networks:
  rust-net:
